//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDAEntities1 : DbContext
    {
        public BDAEntities1()
            : base("name=BDAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Air> Air { get; set; }
        public virtual DbSet<Farma> Farma { get; set; }
        public virtual DbSet<Cologia> Cologia { get; set; }
    
        public virtual ObjectResult<RTS_Result> RTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RTS_Result>("RTS");
        }
    
        public virtual ObjectResult<FDT_Result> FDT(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("A", a) :
                new ObjectParameter("A", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FDT_Result>("FDT", aParameter);
        }
    }
}
